working_directory: .
build_spec:
  name: Golden Roast Tycoon Build
  max_build_duration: 60
  instance_type: mac_mini_m1
  artifacts:
    - android/app/build/outputs/apk/**/*.apk
  scripts:
    - name: Install dependencies
      script: npm install
    - name: Build web assets
      script: npm run build
    - name: Capacitor Sync
      script: npx cap sync android
    - name: Build Android APK
      script: |
        cd android
        ./gradlew assembleDebug

